trigger:
  - main  # or your branch name

pool:
  name: default  # runs on your self-hosted agent

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/build/test-results/test/*.xml'
      testRunTitle: 'Gradle Test Results'
